version: '3'
services:
    notification:
        build:
            context: .
            dockerfile: ./notification/Dockerfile
        image: hack/d2_notification
        container_name: d2_notification
        ports:
            - 127.0.0.1:8889:8888
        volumes:  
            - ./notification/src:/mnt
            - ./model:/model
        #runtime: nvidia
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all
                        

    db:
        build:
            context: ./db
            dockerfile: Dockerfile
        image: hack/d2_db
        container_name: d2_db
        volumes:
             - ./db/sql:/docker-entrypoint-initdb.d
             - ./db/data:/var/lib/mysql
             #- ./db/my.cnf:/etc/mysql/conf.d/my.cnf

    crawl:
        build:
            context: .
            dockerfile: ./crawl/Dockerfile
        image: hack/d2_crawl
        container_name: d2_crawl
        
    analytics:
        build:
            context: .
            dockerfile: ./analytics/Dockerfile
        image: hack/d2_analytics
        container_name: d2_analytics
        ports:
            - 127.0.0.1:8888:8888
        volumes:
            - ./analytics/src:/mnt
            - ./model:/model
